services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.3
    depends_on:
      - elasticsearch
    volumes:
      - ./infrastructure/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "4560:4560"
      - "9600:9600"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      XPACK_FLEET_ENABLED: "false"
      XPACK_FLEET_AGENTS_ENABLED: "false"
    ports:
      - "5601:5601"

  api-gateway-2:
    build:
      context: ./api-gateway
    depends_on:
      - recruitment-service
      - redis
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      APP_SECURITY_JWT_SECRET: ${JWT_SECRET}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_DEFAULT_ZONE:-http://discovery-service:8761/eureka/}
    expose:
      - "8080"

  nginx:
    image: nginx:1.27
    depends_on:
      - api-gateway-1
      - api-gateway-2
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

volumes:
  elastic-data:
