input {
  tcp {
    port => 4560
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => { "service" => "%{app_name}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "recruitment-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
